version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - errcheck
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - inamedparam
    - ineffassign
    - ireturn
    - lll
    - makezero
    - mnd
    - nilnil
    - nlreturn
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
